### ISSUE TITLE
Update news section for Jan, adding all the PWL's.

### ISSUE THREAD

**Issue by zeeshanlakhani** [papers-we-love/papers-we-love.github.io#24]
Anybody, @papers-we-love/collaborators or @papers-we-love/owners, want to take this on. If not, I'll try to get to it tomorrow.

**Comment by johnclaus** [comment]
@zeeshanlakhani I'd be happy to take care of this later tonight (MST).

**Comment by zeeshanlakhani** [comment]
@johnclaus that'd be great! To make things easier, @DarrenN added a way to generate the *monthly news* additions, https://github.com/papers-we-love/papers-we-love.github.io/tree/middleman#creating-a-monthly-meetup-schedule-post. Otherwise, I've just been clicking on each of the meetup pages (and Singapore's FB page), checking for confirmed dates.

**Comment by johnclaus** [comment]
@zeeshanlakhani :+1:

**Comment by zeeshanlakhani** [comment]
@johnclaus just checking-in on this? :)

**Comment by johnclaus** [comment]
@zeeshanlakhani I haven't had a chance to update this yet....nutty week :\

**Comment by zeeshanlakhani** [comment]
@johnclaus no worries. I'll take it on tomorrow or Sunday if you don't have time.

**Comment by zeeshanlakhani** [comment]
@DarrenN saved the day.
