### ISSUE TITLE
Automated data synchronization between meetup and repository

### ISSUE THREAD

**Issue by pravj** [papers-we-love/papers-we-love.github.io#33]
Hi there,

Actually, I observed @DarrenN a few times, editing stats about all the chapters. Their readers count, headcounts for a meetup, number of people with *rsvp* status *yes* and all that.

So, I have this idea in my mind to automates the process.

We can have a heroku application, running a cron job with a customizable time period for the job, where we use the meetup's REST API and look for changes in all the chapters and push the respective changes to the GitHub repo again.

For this, it will need a list of chapters to monitor.

In case, you're thinking about the situation where we need to add/remove a chapter, the application can have a *webhook* support, also associated with the repository.
So, whenever there is a change in the file(probably this, [chapters.yml](https://github.com/papers-we-love/papers-we-love.github.io/blob/middleman/source/chapters.yml)) which contains all the chapters meta data, the *webhook mechanism* will update the chapter list to monitor as well.

I have a working prototype for the idea as well, it doesn't do all the above explained work yet.
I was just ensuring the feasibility of the idea by combining all the associated APIs, and I think it can be done.

Can I have your feedback on this?

**Comment by DarrenN** [comment]
Hi @pravj - thanks for putting some thought into this! 

Currently we do have some automation in place. When you see me updating stats about meetups that is machine generated. We have a [small Clojure app](https://github.com/DarrenN/calligraphus) that works with the Meetup.com API to emit YAML files, which are consumed by [middleman tasks](https://github.com/papers-we-love/papers-we-love.github.io/tree/middleman/tasks) to generate chapter pages and upcoming meetup posts. We are working on expanding this app to cover other APIs besides Meetup.com.

The list of chapters which our clojure app consumes is [here](https://github.com/papers-we-love/papers-we-love.github.io/blob/middleman/source/chapters.yml) (this list is also maintained through a middleman task)  - the API data that middleman consumes for creating pages is [here](https://github.com/papers-we-love/papers-we-love.github.io/blob/middleman/data/meetup/chapters.yml).

Right now the only piece we're missing is the cron job to periodically run tasks and re-deploy to GitHub pages, but it is definitely on our roadmap.

**Comment by pravj** [comment]
Ohh! It's exactly what I was thinking about.
Then it's done champ, you're already doing pretty well.
