### ISSUE TITLE
Need to add Winnipig chapter. 

### ISSUE THREAD

**Issue by zeeshanlakhani** [papers-we-love/papers-we-love.github.io#38]

**Comment by DarrenN** [comment]
Do they have a meetup.com url?

**Comment by DarrenN** [comment]
Indeed they do! https://github.com/papers-we-love/papers-we-love/pull/277/files

**Comment by DarrenN** [comment]
They haven't had the meeting yet - http://www.meetup.com/Papers-We-Love-Winnipeg/events/221603856/

**Comment by zeeshanlakhani** [comment]
They had this one: http://www.meetup.com/Papers-We-Love-Winnipeg/events/220117454/

**Comment by DarrenN** [comment]
derp

**Comment by DarrenN** [comment]
herp

**Comment by DarrenN** [comment]
purp

**Comment by DarrenN** [comment]
:skull:

**Comment by DarrenN** [comment]
Fixed in https://github.com/papers-we-love/papers-we-love.github.io/commit/49668dc0344e10641b2db88c47ee5b6b9d1a3622

Will get picked up and generated in the 1am job
