### ISSUE TITLE
please scrape meetup

### ISSUE THREAD

**Issue by samlecuyer** [papers-we-love/papers-we-love.github.io#40]
LA has an event this month & the meetup needs to get scraped
http://www.meetup.com/Papers-We-Love-LA/events/222365009/

**Comment by DarrenN** [comment]
Hmmm, yep we picked it up in the chapter page - http://paperswelove.org/chapter/la/ but not on the upcoming meetup post, will need to investigate.

**Comment by DarrenN** [comment]
Corrected

**Comment by samlecuyer** [comment]
Thanks @DarrenN !
