### ISSUE TITLE
Make chapter for Brazil

### ISSUE THREAD

**Issue by DarrenN** [papers-we-love/papers-we-love.github.io#46]
Reference: https://github.com/papers-we-love/papers-we-love/pull/329

**Comment by DarrenN** [comment]
Haven't seen a meetup for Brazil since their first in August.

**Comment by hakutsuru** [comment]
@zeeshanlakhani (and DarrenN)...

Looks like brasilia may be roaring back to life, so if this was about getting them on the site, these should be closed. Or should we also add a chapter repo for brasilia?
