### ISSUE TITLE
source/chapters.yml not found

### ISSUE THREAD

**Issue by justincampbell** [papers-we-love/papers-we-love.github.io#47]
I was trying to add a chapter following the instructions in the README, but I'm having trouble:

```
$ bundle exec middleman chapter philadelphia-dc -t "Philadelphia" -u "/chapters/philadelphia" -m "http://meetup.com/Papers-We-Love-Philadelphia"
/Users/Justin/.rubies/ruby-2.2.1/lib/ruby/2.2.0/psych.rb:464:in `initialize': No such file or directory @rb_sysopen - source/chapters.yml (Errno::ENOENT)
```

When I check out the project with a fresh clone, I'm on the `middleman` branch.

Could someone help me get #35 rebased and merged? We had our second meetup tonight, and would love to be listed on the official site.

Thanks!

**Comment by DarrenN** [comment]
Hi @justincampbell  - we'll get it in there. Probably tomorrow morning. The repo is a bit in flux right now as I'm re-tooling portions of the site.

**Comment by DarrenN** [comment]
@justincampbell you're up http://paperswelove.org/chapter/philadelphia/

**Comment by justincampbell** [comment]
Thanks!!! :heart:
