### ISSUE TITLE
Vienna meetup title for April is missing its numbers "(Part of )"

### ISSUE THREAD

**Issue by deltamualpha** [papers-we-love/papers-we-love.github.io#69]
Filing this so I remember to look into it: http://paperswelove.org/2016/news/april-meetups/

**Comment by DarrenN** [comment]
It is missing because I have to do a nasty regex on titles because organizers kept dropping things into their event titles that make no sense. https://github.com/papers-we-love/papers-we-love.github.io/blob/middleman/lib/event-handler.rb#L10

**Comment by deltamualpha** [comment]
https://github.com/papers-we-love/papers-we-love.github.io/tree/remove-part-n-of-n
