### ISSUE TITLE
Columbus chapter has broken image.

### ISSUE THREAD

**Issue by zeeshanlakhani** [papers-we-love/papers-we-love.github.io#93]
http://paperswelove.org/chapter/columbus/

**Comment by DarrenN** [comment]
Is this chapter dead?

**Comment by DarrenN** [comment]
@CraigStuntz are you still the organizer of this chapter?

**Comment by CraigStuntz** [comment]
Yes, I am. I'll fix the image this weekend. We're not dead! Thanks for the mention
