### ISSUE TITLE
Upcoming meetups on chapter pages are displayed in an unexpected order

### ISSUE THREAD

**Issue by leesharma** [papers-we-love/papers-we-love.github.io#95]
### Current Behavior

Upcoming meetups on chapter pages are ordered by date with the highest date first. When a chapter uses recurring events, this means that there are many far-in-the-future placeholder events listed before any *real* upcoming events.

For example, in the [DC Chapter] page (where there are monthly recurring events), there are currently a dozen placeholder events starting at Nov 22, 2017 listed before the actual upcoming events.

### Expected Behavior

As a site visitor, I'd expect to see the most relevant events first. How would you feel about breaking out "Past Events" into a different section and reordering the "Upcoming Events" in ascending order?

It might be worth limiting the number of upcoming events that get shown as well to reduce the length of the page; showing only the next four events plus a "See More..." link to Meetup (for example) would make the page less overwhelming and still (in most cases) just as thorough.

### Steps to Reproduce

Look at the [DC Chapter] page for a live example.

[DC Chapter]: http://paperswelove.org/chapter/washington-dc/

**Comment by DarrenN** [comment]
This should be fixed now as we migrate over to a new system for harvesting data
